django_quiz/django_quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from quiz import views
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user = None):
        return '/quiz/'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/register', MyRegistrationView.as_view(), name = 'registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('quiz/', include('quiz.urls')),
    path('', views.index, name = 'index')
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django_quiz/quiz/urls.py
from django.urls import path
from . import views


app_name = 'quiz'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('select', views.select, name = 'select'),
    path('upload', views.upload, name = 'upload'),
    path('<quiz_name_slug>', views.statistics),
    path('<quiz_name_slug>/start', views.start_test),
    path('<quiz_name_slug>/exam', views.exam),
    path('<quiz_name_slug>/result', views.result),
]

django_quiz/quiz/models.py
import os
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from numpy.random import choice


# Create your models here.
class Quizzes(models.Model):
    name = models.TextField(unique = True, max_length = 250)
    url_name = models.SlugField(unique = True)
    description = models.TextField()
    max_weight = models.FloatField(null = True)
    initial_weight = models.FloatField(null = True)

    def get_deck(self, num_of_questions: int, user):
        """
        :param num_of_questions: number of questions to choose
        :param user: current user id
        :return: list of selected questions' ids
        """
        questions = Questions.objects.filter(quiz_id = self.id)
        progress = []
        for question in questions:
            progress.append(TestProgress.objects.get_or_create(user_id = user,
                                                               quiz_id = self,
                                                               question_id = question,
                                                               defaults = {'weight': self.initial_weight})[0])
        total_weight = sum([i.weight for i in progress])
        weights = [i.weight/total_weight for i in progress]
        try:
            deck_progress = choice(a = progress, size = num_of_questions, replace = False, p = weights)
        except ValueError:
            deck_progress = choice(a = progress, size = len(questions), replace = False, p = weights)
        deck = [i.question_id.id for i in deck_progress]
        return deck

    def calc_weight(self):
        self.max_weight = len(Questions.objects.filter(quiz_id = self.id))
        self.initial_weight = self.max_weight / 2


class Questions(models.Model):
    quiz_id = models.ForeignKey(Quizzes, on_delete = models.CASCADE)
    question_tag = models.TextField()
    question_text = models.TextField()
    question_pic = models.ImageField(blank = True)

    def get_answers(self):
        return Answers.objects.filter(question_id = self.id)

    def get_right_answer(self):
        return Answers.objects.filter(question_id = self.id,
                                      answer_correct = True)

    def user_answered(self, user, correct: bool):
        if correct:
            progress = TestProgress.objects.get(user_id = user,
                                                quiz_id = self.quiz_id,
                                                question_id = self.id)
            progress.weight = progress.weight - 0.5 * (progress.weight - 1)
        else:
            max_weight = self.quiz_id.max_weight # Quizzes.objects.get(id = self.quiz_id.id).max_weight
            progress = TestProgress.objects.get(user_id = user,
                                                quiz_id = self.quiz_id,
                                                question_id = self.id)
            progress.weight = progress.weight + 0.5 * (max_weight - progress.weight)
        progress.last_seen = now()
        progress.seen_times += 1
        progress.save()


class Answers(models.Model):
    question_id = models.ForeignKey(Questions, on_delete = models.CASCADE)
    answer_text = models.TextField()
    answer_pic = models.ImageField(blank = True)
    answer_correct = models.BooleanField(default = False)


class Progress(models.Model):
    user_id = models.ForeignKey(User, on_delete = models.CASCADE)
    last_use = models.DateTimeField(default = now)
    quiz_id = models.ForeignKey(Quizzes, on_delete = models.CASCADE)
    learned_percent = models.FloatField(default = 0)
    seen_percent = models.FloatField(default = 0)

    def update_percentage(self):
        progress_rows = TestProgress.objects.filter(user_id = self.user_id,
                                                    quiz_id = self.quiz_id,)
        # quiz_row = Quizzes.objects.get(id = self.quiz_id.id)
        # max_weight = quiz_row.max_weight
        max_weight = self.quiz_id.max_weight
        num_of_rows = len(progress_rows)
        seen = 0
        learned = 0
        last_use = datetime(year = 1970, month = 1, day = 1)
        for row in progress_rows:
            if row.weight > max_weight / 3 and row.seen_times >= 2:
                learned += 1
            if row.seen_times:
                seen += 1
            try:
                if row.last_seen > last_use:
                    last_use = row.last_seen
            except TypeError:
                pass
        self.learned_percent = (learned / num_of_rows) * 100
        self.seen_percent = (seen / num_of_rows) * 100
        return self.save()


class TestProgress(models.Model):
    user_id = models.ForeignKey(User, on_delete = models.CASCADE)
    quiz_id = models.ForeignKey(Quizzes, on_delete = models.CASCADE)
    question_id = models.ForeignKey(Questions, on_delete = models.CASCADE)
    weight = models.FloatField(default = 0)
    seen_times = models.IntegerField(default = 0)
    last_seen = models.DateField(null = True)

django_quiz/quiz/forms.py
from django import forms


class QuestionForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.question = kwargs.pop('question', None)
        super().__init__(*args, **kwargs)
        answers = self.question.get_answers()
        self.choices = [(a.id, a.answer_text) for a in answers]
        self.fields['answers'] = forms.MultipleChoiceField(choices = self.choices,
                                                           widget = forms.CheckboxSelectMultiple)


class UploadTestForm(forms.Form):
    file = forms.FileField(label = "Select a file", required = True)

django_quiz/quiz/views.py
import os, shutil

from random import shuffle

from django.http import HttpResponse
from django.shortcuts import render, redirect
from quiz.models import Quizzes, Questions, Progress, Answers
from quiz.forms import QuestionForm, UploadTestForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from quiz.utils import import_quiz


# Create your views here.
def index(request):
    return render(request, 'quiz/index.html')


@login_required
def select(request):
    quizzes = Quizzes.objects.all()
    context_dict = {'quizzes': quizzes}
    return render(request, 'quiz/select.html', context_dict)


@login_required
def statistics(request, quiz_name_slug):
    quiz = Quizzes.objects.get(url_name = quiz_name_slug)
    user = request.user
    progress = Progress.objects.get_or_create(user_id = user, quiz_id = quiz)[0]
    context_dict = {'progress': progress, 'quiz': quiz}
    return render(request, 'quiz/statistics.html', context_dict)


@login_required
def start_test(request, quiz_name_slug):
    num_of_questions = int(request.GET.get('num', '20'))
    is_exam = bool(int(request.GET.get('exam', '0')))
    current_quiz = Quizzes.objects.get(url_name = quiz_name_slug)
    request.session['exam'] = is_exam
    request.session['current_test'] = current_quiz.id
    request.session['answered'] = 0
    request.session['user_answers'] = {}  # {question_id: [answers_id]}
    request.session['current_deck'] = current_quiz.get_deck(num_of_questions, request.user)
    request.session['deck_length'] = len(request.session['current_deck'])
    return redirect(f'/quiz/{quiz_name_slug}/exam')


@login_required
def exam(request, quiz_name_slug):
    if request.method == 'GET':
        try:
            question_id = request.session.get('current_deck', []).pop()
            request.session['current_question'] = question_id
            question = Questions.objects.get(id = question_id)
            form = QuestionForm(question = question)
            pics = {answer.id: answer.answer_pic for answer in question.get_answers()}
            context_dict = {'question': question, 'form': form, 'pics': pics,
                            'quiz_name_slug': quiz_name_slug,
                            'answered': request.session.get('answered', 0),
                            'deck_length': request.session.get('deck_length', 0)}
            return render(request, 'quiz/question.html', context_dict)
        except IndexError:  # questions in deck are finished
            print('deck is empty')
            return redirect(f'/quiz/{quiz_name_slug}/result')
    elif request.method == 'POST':
        question_id = request.session.get('current_question', 0)
        question = Questions.objects.get(id = question_id)
        form = QuestionForm(request.POST, question = question)
        answered = request.session.get('answered', 0)
        deck = request.session.get('current_deck', [])
        if form.is_valid():
            user_answers = set(form.cleaned_data['answers'])
            correct_answers = set(str(answer.id) for answer in question.get_right_answer())
            user_answer_is_correct = user_answers == correct_answers
            question.user_answered(request.user, user_answer_is_correct)
            if not user_answer_is_correct:
                request.session['user_answers'][question_id] = list(user_answers)
            # in learning mode show right answer after each question, exam mode shows answers only in the end
            if request.session.get('exam', False) or user_answer_is_correct:
                request.session['answered'] = answered + 1
                return redirect(f'/quiz/{quiz_name_slug}/exam')
            else:
                deck.append(question_id)
                shuffle(deck)
                request.session['current_deck'] = deck
                return redirect(f'/quiz/{quiz_name_slug}/result')
        else:
            deck.append(question_id)
            shuffle(deck)
            request.session['current_deck'] = deck
            return redirect(f'/quiz/{quiz_name_slug}/exam')

@login_required
def result(request, quiz_name_slug):
    try:
        question_id, answer_ids = request.session['user_answers'].popitem()
        request.session.save()
        question = Questions.objects.get(id = question_id)
        user_answers = [Answers.objects.get(id = answer_id) for answer_id in answer_ids]
        right_answers = question.get_right_answer()
        context_dict = {'question': question, 'user_answers': user_answers,
                        'right_answers': right_answers, 'quiz_name_slug': quiz_name_slug}
        return render(request, 'quiz/result.html', context_dict)
    except KeyError:
        progress = Progress.objects.get(user_id = request.user,
                                        quiz_id = request.session['current_test'])
        progress.update_percentage()
        return redirect(f"/quiz/{quiz_name_slug}")

@login_required
def upload(request):
    if request.method == "GET":
        form = UploadTestForm()
        context_dict = {'form': form}
        return render(request, "quiz/upload.html", context_dict)
    elif request.method == "POST":
        form = UploadTestForm(request.POST, request.FILES)
        if form.is_valid():
            if 'file' in request.FILES:
                result = import_quiz(request.FILES['file'])
                print(result)
        return redirect('/quiz/select')

django_quiz/templates/quiz/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="http://getbootstrap.com/examples/sticky-footer-navbar/sticky-footer-navbar.css" rel="stylesheet">
    <title>{% block title %}Hello!{% endblock %}</title>
  </head>
  <body>
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'quiz:index' %}">{% block brand %}Quiz!{% endblock %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'quiz:select' %}">Select quiz</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'quiz:upload' %}">Upload your quiz</a>
            </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link disabled" href="{% url 'quiz:index' %}">Select quiz</a>
              </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav mr-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registration_register' %}">Sign Up!</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main role="main" class="flex-shrink-0">
      <div class="container-fluid mt-5">
        <div class="container pt-4">
          {% block body %}
          <h1>Hello, world!</h1>
          {% endblock %}
        </div>
      </div>
    </main>
    {% block footer %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

django_quiz/templates/quiz/base_with_footer.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block footer %}
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>
{% endblock %}

django_quiz/templates/quiz/bootstrap_template.html
<!doctype html>
<html lang="ru" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Пример на bootstrap 4: Прижатый футер отображается в нижней части страницы, когда содержимое окна слишком короткое. Панель навигации в верхней части.">

    <title>Прижатый футер с меню | Sticky Footer Navbar Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="sticky-footer-navbar.css" rel="stylesheet">

  </head>

  <body class="d-flex flex-column h-100">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-4481610-59', 'auto');
  ga('send', 'pageview');

</script>

<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter39705265 = new Ya.Metrika({ id:39705265, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/39705265" style="position:absolute; left:-9999px;" alt="Yandex.Metrika" /></div></noscript> <!-- /Yandex.Metrika counter -->

    <header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Fixed navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</header>

<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Sticky footer with fixed navbar</h1>
    <p class="lead">Pin a footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with <code>padding-top: 60px;</code> on the <code>main &gt; .container</code>.</p>
    <p>Back to <a href="/docs/4.3.1/examples/sticky-footer/">the default sticky footer</a> minus the navbar.</p>
  </div>
</main>

<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/docs/4.3.1/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>

</body>
</html>

django_quiz/templates/quiz/index.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container-fluid">
    <h1>Welcome to Quiz system!</h1>
    <div class="container">
        <p>
        It is flexible system, where you can improve your knowledge!<br>
        You can select one of previously uploaded quizzes or upload your own!<br>
        Ready?

        {% if user.is_authenticated %}
        <a href="{% url 'quiz:select' %}">Select test</a>
        {% else %}
        <a href="{% url 'auth_login' %}">Log In</a> or <a href="{% url 'registration_register' %}">Sign Up!</a>
        {% endif %}
        </p>
    </div>
</div>

{% endblock %}

django_quiz/templates/quiz/question.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% load django_utils %}
{% block body %}
<div class="card mb-5">
        <div class="row no-gutters">
            {% if question.question_pic %}
                <div class="col-md-4">
            {% else %}
                <div class="col-md-12">
            {% endif %}
                <div class="card">
                    <div class="card-header">Question: {{ question.question_tag }}</div>
                    <div class="card-body">
                        <div class="card-text">
                            {{ question.question_text }}
                        </div>
                    </div>
                </div>
            </div>
        {% if question.question_pic %}
            <div class="col-md-8"><img class="img-fluid" src="{{ question.question_pic.url }}" /></div>
        {% endif %}
        </div>
    <div>
</div>
</div>
<div class="container">
    <form id="answer_form" method="post" action="/quiz/{{ quiz_name_slug }}/exam">
        {% csrf_token %}
        <div class="card-deck mb-5">
                {% for answer_id, answer_text in form.answers.field.choices %}
                    <div class="card border-light">
                        {% if pics|get_value_from_dict:answer_id %}
                            {% with pic=pics|get_value_from_dict:answer_id %}
                            <img src="{{ pic.url }}" class="card-img-top img-fluid" />
                            {% endwith %}
                        {% endif %}
                        <div class="btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-primary btn-block">
                                <input type="checkbox" autocomplete="off" name="answers" value="{{ answer_id }}">{{ answer_text }}
                            </label>
                        </div>
                    </div>
                {% endfor %}
        </div>
        <input type="submit" name="submit" value="Submit" class="btn btn-primary btn-active mb-5">
    </form>
</div>
<div>
    <progress value="{{ answered }}" max="{{ deck_length }}"></progress>
</div>
{% endblock %}

django_quiz/templates/quiz/result.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block body %}
<div class="card mb-5">
    <div class="row no-gutters">
        {% if question.question_pic %}
            <div class="col-md-4">
        {% else %}
            <div class="col-md-12">
        {% endif %}
                <div class="card">
                    <div class="card-header">Question: {{ question.question_tag }}</div>
                    <div class="card-body">
                        <div class="card-text">
                            {{ question.question_text }}
                        </div>
                    </div>
                </div>
            </div>
        {% if question.question_pic %}
            <div class="col-md-8"><img class="img-fluid" src="{{ question.question_pic.url }}" /></div>
        {% endif %}
    </div>
</div>
<div class="card-deck mb-5">
    <div class="card border-success" id="right_answers">
        <div class="card-header bg-transparent">Right answers:</div>
        <div class="card-body">
            <ul>
                {% for answer in right_answers %}
                <li>{{ answer.answer_text }}
                    {% if answer.answer_pic %}
                        <img class="img-fluid" src="{{ answer.answer_pic.url }}" />
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="card border-danger" id="user_answers">
        <div class="card-header">You answered:</div>
        <div class="card-body">
            <ul>
                {% for answer in user_answers %}
                <li>{{ answer.answer_text }}
                    {% if answer.answer_pic %}
                        <img class="img-fluid" src="{{ answer.answer_pic.url }}" />
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<a class="btn btn-primary" role="button" href="/quiz/{{ quiz_name_slug }}/exam">OK</a>
{% endblock %}

django_quiz/templates/quiz/select.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block body %}
<h1 class="h5">Please select test</h1>
<ul>
{% for quiz in quizzes %}
    <li><a href="/quiz/{{ quiz.url_name }}"><b>{{ quiz.name }}</b> - {{ quiz.description }}</a></li>
{% endfor %}
</ul>
{% endblock %}

django_quiz/templates/quiz/statistics.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block body %}
<h1 class="h5">Hello, {{ user }}!</h1>
<div>
    You selected test: {{ quiz.name }}<br/>
    Your last use of this test was: {{ progress.last_use }}<br/>
    You have seen {{ progress.seen_percent }}% of all questions in this quiz<br/>
    You have learned {{ progress.learned_percent }}% of this quiz.<br/>
</div>
<div>
    <a href="/quiz/{{ quiz.url_name }}/start">Try or learn</a><br/>
    <a href="/quiz/{{ quiz.url_name }}/start?exam=1&num=20">Examine yourself!</a>
</div>
{% endblock %}

django_quiz/templates/quiz/upload.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block body %}
<h1 class="h5">Uploading your test</h1>
File format for uploading:<br>
You need to prepare zip-archive with this data (no folders):<br>
<div>
    <b>test.txt</b><br>
    FIle containing questions and answers, marked with special tags. Each tag must be in beginning of the line. <br>
    <ul>
        <li><b>&lt%%ID&gt</b> - Number or tag of question</li>
        <li><b>&lt%%Q&gt</b> - Text of your question</li>
        <li><b>&lt%%QP&gt</b> - Filename of picture embedded to your question. This file must be in archive too. Optional</li>
        <li><b>&lt%%AC&gt</b> - Text of correct answer for your question</li>
        <li><b>&lt%%A&gt</b> - Text of incorrect answer for your question</li>
        <li><b>&lt%%AP&gt</b> - Filename of picture for current answer. Optional</li>
    </ul>
</div>
<div>
    <b>description.txt</b><br>
    File with description and name of the test. Must contain three lines.
    <ul>
        <li>url name, latin, must not contain spaces</li>
        <li>quiz name to show in list</li>
        <li>description of the quiz</li>
    </ul>
</div>
<div>
    If you need pictures in your quiz place picture files in archive too, without folders
</div>
<div>
    <form id="upload" method="post" action="/quiz/upload" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}<br>
        <input type="submit" name="submit" value="Upload">
    </form>
</div>
{% endblock %}